apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  type: LoadBalancer
  selector:
    app: redis  # 匹配 Deployment 的 Pod 标签
  ports:
  - port: 6379        # Service 暴露端口
    targetPort: 6379  # Pod 内部端口
    protocol: TCP